language: ruby
rvm:
  - 2.2
  - jruby
  - 2.0.0-p247
before_script:
  - ls -la
  - eval `ssh-agent -s`
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_326d9b317a06_key -iv $encrypted_326d9b317a06_iv -in travis_key.enc -out travis_key -d
  - cp travis_key ~/.ssh/
  - chmod 600 ~/.ssh/travis_key 
  - ssh-add ~/.ssh/travis_key
script:
  - echo hoge > hoge.txt
after_success:
  - echo success.
after_failure:
  - echo failed.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: develop
